- README.md
Since the engine-cli will be the entry point for many users, I was thinking, so should be the repository, Therefore I've written a README based upon the excellent structure of [prisma](https://github.com/prisma/prisma). Some of the content is still placeholder and will need to be filled out further.
> Proposal for a README

- cmd/srcd/cmd/sql.go
Sorry for merging directly, feel free to revert but we can't have queries timeout after 10 mins.
Signed-off-by: Eiso Kant <eiso@sourced.tech>
> Increases context timeout from 10 to 1440 minutes

- cmd/srcd/cmd/kill.go
- components/components.go
- docs/commands.md
Fix: #61 #69
As described in the issue the current behavior is very strange.
This PR changes the default. `srcd kill` won't remove images anymore by default. But only with new flag `--with-images`
> Kill: don't remove images by default

- README.md
Usually HEAD refers to the latest revision, and the phrase "commit count in HEAD" thus means "commit count in the latest commit" which makes no sense. We really mean the HEAD reference here, and I link to the description in the official documentation.
> Link to what is HEAD in README

- .travis.yml
Follow update to CI guide: https://github.com/src-d/guide/pull/276
> Remove go tip from CI

- components/components.go
- docker/docker.go
Fix #62
it removes the network. Renaming/splitting of the kill command should be handled in a separate issue.
> remove network on purge

- cmd/srcd-server/engine/components.go
- cmd/srcd-server/engine/drivers.go
- cmd/srcd-server/engine/parse.go
- cmd/srcd-server/engine/sql.go
- cmd/srcd-server/engine/web.go
- cmd/srcd/daemon/daemon.go
- docker/docker.go
We will need to pass request id around for logs and it can be useful for some other improvements later.
Extracted from #88
> Pass context around

- docker/docker.go
Fix #132
Current timeout is 1 second which is definitely not enough for some containers.
30 seconds looks reasonable.
> Increase container remove timeout

- cmd/srcd/cmd/components.go
- components/components.go
Related to #118.
This PR adds extra info to `components list`.
Before:
```
$ srcd components list 
srcd/cli-daemon:latest
srcd/gitbase:v0.17.1
bblfsh/bblfshd:v2.9.2-drivers
$ srcd components list -a
srcd/cli-daemon:latest
srcd/gitbase:v0.17.1
bblfsh/bblfshd:v2.9.2-drivers
srcd/cli-daemon:v0.2.0
srcd/gitbase-web:latest
bblfsh/bblfshd:latest
bblfsh/bblfshd:v2.9.1
bblfsh/bblfshd:v2.9.0-drivers
```
After:
```
$ srcd components list 
IMAGE                            INSTALLED    RUNNING    CONTAINER NAME
bblfsh/bblfshd:v2.9.2-drivers    yes          no         srcd-cli-bblfshd
bblfsh/web:v0.7.0                no           no         srcd-cli-bblfsh-web
srcd/cli-daemon:latest           yes          yes        srcd-cli-daemon
srcd/gitbase-web:v0.3.0          no           no …
```
> Format components list output as table

- docs/commands.md
This command is not implemented; instead (it appears) the intended use is to
pass "-m native" to the "srcd parse uast" subcommand.
Signed-off-by: M. J. Fromberger <michael.j.fromberger@gmail.com>
> docs: Remove reference to "srcd parse native".

- cmd/srcd/cmd/components.go
- cmd/srcd/daemon/daemon.go
- components/components.go
Using `Component`s for `srcd components install` means that we allow to install only the exact images (and versions) engine manages, instead of any image with the `srcd/` or `bblfsh/` prefix as we do in master.
With this PR we also get a nicer error when the component to install is not found:
```
$ srcd install srcd/lookout
Error: srcd/lookout is not valid. Component must be one of [srcd/cli-daemon, srcd/gitbase, srcd/gitbase-web, bblfsh/bblfshd, bblfsh/web]
```
> Use Components for srcd components install

- docker/docker.go
Part of #164.
The code does a container creation. If it fails, it checks if a container with that name already exists, deletes it, and retries.
The problem is that in case no other container exists, we were returning the `Info` error message, instead of the `ContainerCreate` error.
So for `srcd init /tmp/nope` & `srcd web sql` you get this message in master:
```
FATA[0010] could not start gitbase web client at port 8080: rpc error: code = Unknown desc = could not create srcd-cli-gitbase: could not create container srcd-cli-gitbase: container not found 
```
And with this PR you get the real reason:
```
FATA[0009] could not start gitbase web client at port 8080: rpc error: code = Unknown desc = could not create srcd-cli-gitbase: could not create container srcd-cli-gitbase: Error response …
```
> Fix error returned for container creation failures

- cmd/srcd/cmd/init.go
Working on #166 I've realized that it doesn't make sense to try to create containers with an invalid workdir, when beforehand is so simple.
> Check workdir is valid before starting containers

- cmd/srcd-server/engine/components.go
- cmd/srcd-server/engine/parse.go
- components/components.go
Fix #159, Fix #160.
This PR updates bblfsd to v2.11.0.
I also included here the removal of the drivers installation. The reason why it was not removed before is that the `cpp` driver was not included in the `2.10.0` image (see [context here](https://github.com/src-d/engine/pull/135)). In 2.11.0 it is included, so we can skip the driver installation step.
I also removed the bblfsd volume, since it was used to store the installed drivers only.
I did not remove any of the code to install drivers because we might use it in the future. For example if we need to install specific drivers versions.
> Bblfshd v2.11.0

- docs/architecture.md
Removing enclosing `p`;
If using it to enclose an image, the image won't be shown.
> Remove p html tag

- cmd/srcd/cmd/init.go
By using the standard `Args` key of Cobra `Command`, the error message in case of a number of arguments > 1 changes from:
```
✘  se7entyse7en in ~/Projects/src-d/engine/cmd/srcd (init-cmd-clean)  $ srcd init foo bar                                                                                        [12/26/18 | 13:06:40.051]
FATA[0000] invalid number of arguments given, expecting 0 or 1
```
to:
```
✔  se7entyse7en in ~/Projects/src-d/engine/cmd/srcd (init-cmd-clean)  $ go run main.go init foo bar                                                                              [12/26/18 | 13:06:17.418]
Error: accepts at most 1 arg(s), received 2
Usage:
srcd init [flags]
Flags:
-h, --help   help for init
Global Flags:
--config string   config file (default is $HOME/.srcd.yaml)
-v, --verbose …
```
> Just some improvements on init.go

- cmd/srcd/cmd/parse.go
> Improves logging for unknown bblfsh driver in parse cmd

- cmd/srcd/cmd/root.go
- cmd/srcd/cmd/sql.go
Fix: #152
1st commit implements installation before starting repl.
2nd commit fixes a bug that we still read logs after started channel is closed.
Example output:
```
$ go run cmd/srcd/main.go sql
INFO[0005] this is taking a while, if this is the first time you launch sql client, it might take a few more minutes while we install all the required images
INFO[0005] installing \"bblfsh/bblfshd:v2.11.0-drivers\"
INFO[0102] installed \"bblfsh/bblfshd:v2.11.0-drivers\"
INFO[0102] starting bblfshd daemon
gitbase> select * from repositories;
+---------------+
| REPOSITORY ID |
+---------------+
| repos         |
+---------------+
```
> Sql install deps

- cmd/srcd-server/engine/components.go
Fix #197, #204.
After reading the descriptions in #197 & #204 the only workaround I can think of is increasing the timeout. 30 seconds sounds like it should be enough to create a container, but maybe in mac OS it is different since it does nested virtualization.
While increasing the timeout may not address the problem, maybe it allows enough time for the docker api to return a proper error with more information.
> Increase start containers timeout to 60s

- components/components.go
There aren't release notes for the `-drivers` image, but this one includes the new `csharp` driver.
> Update bblfshd to v2.11.6

- cmd/srcd/cmd/web.go
fix: #255
Closing signal channel should be the last thing to do before exiting.
Another solution would be not to close it at all because we exit anyway.
Signed-off-by: Maxim Sukharev <max@smacker.ru>
> fix panic on stopping web command

- .gitignore
- Makefile
- cmd/srcd-server/Dockerfile
- cmd/test-utils/common.go
- components/components.go
- docker/dockerhub.go
Part of #232.
This reverts some of the changes made in #302 related to the build flags, and having a different special build for `make test-integration`.
With this PR these two things are equivalent:
```
make test-integration
```
```
make build
make docker-build
make test-integration-no-build
```
The advantage is that we are testing the normal build process. Which means that you can for example download the binary for v0.11.0-rc.3, put it in `build/engine_GOOS_GOARCH/srcd`, and run `make test-integration-no-build` (if you do you will see that the current test detects the bug #252).
> Use normal build for integration tests

- cmd/srcd/cmd/components_test.go
Part of #232.
Adds tests for `srcd components`.
It is expected to fail until #310 is merged and rebased. The tests here use the normal container names without the `integration-testing-` prefix.
> Add integration tests for components cmd

- docker/dockerhub.go
- docker/dockerhub_test.go
Fix: #252
For pre-release client version it will always return exact the same
version of the server due to unstable nature of pre-releases and
possible breaking changes between them or the next stable version.
Signed-off-by: Maxim Sukharev <max@smacker.ru>
> add support for pre releases

- cmd/srcd/cmd/parse_test.go
- cmd/srcd/cmd/testdata/LICENSE
- cmd/srcd/cmd/testdata/README.md
- cmd/srcd/cmd/testdata/hello-py3.py
- cmd/srcd/cmd/testdata/hello.bash
- cmd/srcd/cmd/testdata/hello.cpp
- cmd/srcd/cmd/testdata/hello.cs
- cmd/srcd/cmd/testdata/hello.go
- cmd/srcd/cmd/testdata/hello.java
- cmd/srcd/cmd/testdata/hello.js
- cmd/srcd/cmd/testdata/hello.php
- cmd/srcd/cmd/testdata/hello.py
- cmd/srcd/cmd/testdata/hello.rb
Part of #232.
Tests for `srcd parse drivers`, `srcd parse lang`, `srcd parse uast`
> Add integration tests for parse cmd

- cmd/srcd/cmd/components.go
- cmd/srcd/cmd/components_test.go
- components/components.go
- docker/docker.go
fix: #300
Integration test checks that the correct port is displayed in `TestListInit`.
Please let me know if you think I should remove it from there and add another test case especially for the ports.
> show public ports of components in components list

- api/config.go
- cmd/srcd-server/engine/components.go
- cmd/srcd-server/engine/drivers.go
- cmd/srcd-server/engine/parse.go
- cmd/srcd-server/engine/sql.go
- cmd/srcd-server/engine/web.go
- cmd/srcd/daemon/daemon.go
- components/components.go
Fix #240.
Instead of api/config.go I decided to put the port definitions in components.go. The reason is because these private ports cannot be configured, they simply define the private port used by the docker images, which are also defined in components.go.
For config.go I didn't use the private port in the public port default value of GitbaseWeb and BblfshWeb. Instead of 8080 for both we use 8080 and 8081, and I think it made sense to leave them hardcoded.
> Group containers private ports const definitions

- cmd/srcd/cmd/errors.go
- cmd/srcd/cmd/prune.go
- cmd/srcd/cmd/prune_test.go
- docker/docker.go
Part of #232.
Tests for `srcd prune`.
This test suite does not test the `--with-images` flag.
If the tests are run with `make test-integration` the daemon image will be the one build locally (e.g. srcd/cli-daemon:dev-b72f1fe), and deleting this image would make all the other tests fail.
> Add integration tests for prune cmd

- components/components.go
New bblfsh release, https://github.com/bblfsh/bblfshd/releases/tag/v2.12.0
> Update bblfsh to v2.12.0

- cmd/srcd/daemon/daemon.go
fix: #380
I didn't delete `CleanUp` function because I'm going to use it in state PR. And we might want to clean something else later.
I also didn't change the changelog. Because we still clean indexes on prune we just do it differently.
> remove prune of old gitbase indexes

- cmd/srcd/cmd/components_test.go
- cmd/srcd/cmd/init_test.go
- cmd/srcd/cmd/parse_test.go
- docker/dockerhub.go
Fix #392.
When a build was done with version `dev-xxxx` the code did no go to dockerhub to look for newer releases. 
But when the release tag was created, the tests on travis use a real semver tag before the image is uploaded to dockerhub. Some tests failed because in this case there is a warning message:
```
WARN[0009] unable to list the available daemon versions on Docker Hub: can't find compatible image in docker registry for srcd/cli-daemon 
```
In this PR I have removed the special case for `dev-xxxx` versions, and I have updated tests to not rely on the exact output logs.
> Fix integration tests failing for release tags

- cmd/srcd/cmd/prune_test.go
- cmd/srcd/cmd/sql.go
- docker/docker.go
Fix #371.
There were 2 problems:
- `docker.withVolume` was creating an extra anonymous volume definition.
- the mysql docker image contains a volume definition in the image dockerfile.
I couldn't find a way to force the mysql container to start without a volume, so I added the `RemoveVolumes` option to `RemoveContainer`. It seems to apply only to the anonymous volumes, and the named volumes with index data are not deleted. This is similar to `docker rm --volumes`.
There was a problem in the `sql` command. It was using `os.Exit`, so the `defer stopMysqlClient()` was never executed. The mysql container was left stopped, and the associated volume was also not cleaned.
> Deal with anonymous dangling volumes

- CHANGELOG.md
I have tested with 0.11.0 and #371 was already present, so it needs to be part of the changelog.
I also modified the text about `prune` cleaning volumes. #352 was actually about `prune` cleaning the `~/.srcd/gitbase` dir, which does not exist anymore.
> Update changelog for 0.12.0-rc.2

- CHANGELOG.md
- README.md
Prepare the changelog for 0.12.0.
I also removed the mentions about windows being experimental. Now we have the same integration tests in linux and windows. I think we can consider it has the same level of support.
> Bump changelog to v0.12.0

- .travis.yml
- Makefile
- cmdtests/prune_test.go
- docker/docker.go
Closes #374.
Adds integration testing for the `srcd prune --with-images` and runs it on CI. Running this test is disabled by default and can be enabled by settings the env var `TEST_PRUNE_WITH_IMAGE=true` as in [here](https://github.com/src-d/engine/pull/405/files#diff-354f30a63fb0907d4ad57269548329e3R35).
> Adds integration testing for prune --with-images command

- cmd/srcd/cmd/components.go
- cmd/srcd/cmd/drivers.go
- cmd/srcd/cmd/table.go
- cmd/srcd/cmd/table_test.go
- cmdtests/parse_test.go
Closes #322.
This adds two functions `PrintTable` and `PrintDefaultTable`. This simplifies table printing and helps to have a consistent styling for all of them. It's also easier to eventually change the style of all tables.
> Adds an utility to print tables

- cmdtests/gitbase_back_comp_test.go
- cmdtests/sql_index_util.go
- cmdtests/sql_test.go
> integration tests: wait for index creation 

- README.md
Fix #445, adding docs on how to connect to gitbase directly if you need to.
I used the `start` command from #433 even though it's not yet in master, because it should be before the next release.
> Add gitbase connection details to readme

- CHANGELOG.md
- README.md
- cmd/srcd/cmd/drivers.go
- cmd/srcd/cmd/parse.go
- cmdtests/parse_test.go
- docs/commands.md
> Rename 'parse drivers list' sub command to 'parse drivers'

- CHANGELOG.md
- cmd/srcd/cmd/parse.go
- cmdtests/parse_test.go
This is a workaround for #297.
The command now does not try to check if the file language is in the list of bblfsh drivers. But if bblfsh reports that the parsing failed because of a missing driver, engine will still print the same nice error message with the current list of supported languages.
It works for
- enry `c#` -> bblfsh `csharp`
- enry `c++` -> bblfsh `cpp`.
It still fails for
- enry `shell` -> bblfsh `bash`.
Unfortunately now that the tests parse the cpp and csharp files, they fail, so I had to disable them.
See https://github.com/bblfsh/cpp-driver/issues/31, https://github.com/bblfsh/bblfshd/issues/259
> srcd parse: do not check the list of languages

- CHANGELOG.md
- cmd/srcd/cmd/config.go
- cmd/srcd/config/config.go
- cmdtests/config_test.go
Fix #422.
I only knew about `EDITOR` env var. Apparently for historic reasons many programs look first for an editor set in `VISUAL`, and fall back to `EDITOR` if that one is not set.
If there isn't an editor set I chose to use `nano` for macos and linux. It should be installed by default, and if you don't have an editor preference `nano` will be more user friendly than `vim` or `emacs`.
> New command srcd config

- CHANGELOG.md
- cmd/srcd-server/engine/components.go
- cmd/srcd-server/engine/sql.go
- docker/docker.go
Fix #279.
Queries like `select * from files order by...` can freeze the system. It's happened to me a few times, and I've had to reboot my laptop. This PR adds a limit on the container access to the host CPU.
I chose a limit of 75% a bit arbitrarily. After playing around with a few values it seemed like the sweet spot.
> Add cpu limits to gitbase container

- cmdtests/sql_interactive_test.go
- cmdtests/sql_test.go
pty.Start isn't exported on windows which fails build.
I moved interactive repl test into separate file with !windows build tag
Signed-off-by: Maxim Sukharev <max@smacker.ru>
> fix integration tests build on windows

- Makefile
- cmd/srcd-server/engine/web.go
- cmdtests/init_test.go
- run-integration-tests.bat
Partially address #456.
I wrote a proper description for each commit.
> Integration test fixes

- cmdtests/common_test.go
The timeout for pending messages in the test
`StreamLinifierTestSuite/TestSlowPendingMessage` is incorrect. This test
is supposed to test that slow messages are considered as part
of different lines, but the timeout value being used is the same of
the time that passes between each message. This leads to a
non-deterministic output. This is fixed by decreasing the timeout the
`StreamLinifier` is configured with.
Signed-off-by: Lou Marvin Caraig <loumarvincaraig@gmail.com>
> Fix flaky `StreamLinifierTestSuite/TestSlowPendingMessage` test
