cmd/srcd-server/Dockerfile, cmd/srcd-server/engine/component_test.go, cmd/srcd-server/engine/components.go, cmd/srcd-server/engine/engine.go, cmd/srcd-server/engine/parse.go, cmd/srcd-server/engine/sql.go, cmd/srcd-server/main.go, cmd/srcd/daemon/daemon.go, components/components.go, docker/docker.go
Depends on #16 
Closes #13 
Closes #12
=>  *: implement driver and index persistence 

.travis.yml
Signed-off-by: Miguel Molina <miguel@erizocosmi.co>
=> ci: restore releases deployment

cmd/srcd-server/engine/web.go
=> web-sql: make gitbase-web serve on correct port

cmd/srcd/cmd/sql.go
As a result of this changes all statements must finish with a ;.
This is consistent with the behavior of the standard mysql client.
Fixes #27.
=> sql: provide support for multilines

cmd/srcd-server/engine/components.go, cmd/srcd-server/engine/sql.go, cmd/srcd/cmd/sql.go
This might cause conflicts if the port is already in use.
Updates #29.
=> sql: expose the gitbase port to the docker host

cmd/srcd-server/Dockerfile
=> daemon: use alpine as base image on second docker build stage

README.md, SUMMARY.md, examples/README.md
- Add `SUMMARY.md` for Gitbook docs
- Move some examples from `README.md` to `examples/README.md`
=> Add gitbook docs summary & move examples

cmd/srcd-server/engine/components.go, cmd/srcd-server/engine/parse.go, cmd/srcd/cmd/kill.go, components/components.go, docker/docker.go, docs/commands.md
=> cmd: add kill command

cmd/srcd-server/engine/components.go, cmd/srcd-server/engine/sql.go, cmd/srcd/daemon/daemon.go, components/components.go
Fix: #73 #75
We don't need pilosa image anymore.
=> remove pilosa

README.md
=> Link to gitbase-web in the README

README.md
The link was not working properly
=> Fix UAST link in readme

README.md
Signed-off-by: Fernanda Gomes <fergomes@gmail.com>
=> add ';' by the end of sql queries examples

cmd/srcd-server/engine/drivers.go
Bblfshd changed the way how it returns error about already installed drivers
=> Fix detection of driver already installed error

cmd/srcd/cmd/init.go, docker/docker.go
=> make docker.Info work with stopped containers

docker/docker.go
=> make logs about network more human-friendly

.travis.yml
Using Xenial -> no need for the toolchain hacks
=> Simplify Travis config

components/components.go
=> Fix component versions

README.md
fix #65
`;` were added in another PR before
=> fix example for new gitbase version

cmd/srcd/cmd/version.go, cmd/srcd/main.go
=> fix version command

README.md
I made some grammatical changes to the README file, including the changing of spelling, and phrasing of sentences. Hope this helps! ✅
=> Minor grammatical updates to the README file.

cmd/srcd-server/engine/parse.go, cmd/srcd-server/engine/sql.go, cmd/srcd-server/engine/web.go, components/components.go
Few commits before I defined fixed version of the dependencies but apparently they are just ignored and the engine still installs latest always.
=> Fix ignoring defined version of the components

cmd/srcd-server/engine/components.go, cmd/srcd-server/engine/parse.go, cmd/srcd-server/engine/sql.go, cmd/srcd-server/engine/web.go
Try to fix #63 #106 
There are also timeouts on cli side but they are huge.
I can't reproduce those errors but 5 seconds can be not enough sometimes indeed.
=> increase timeout for components to start

cmd/srcd/daemon/daemon.go, cmd/srcd/main.go, go.mod, go.sum, vendor/github.com/blang/semver/.travis.yml, vendor/github.com/blang/semver/LICENSE, vendor/github.com/blang/semver/README.md, vendor/github.com/blang/semver/json.go, vendor/github.com/blang/semver/package.json, vendor/github.com/blang/semver/range.go, vendor/github.com/blang/semver/semver.go, vendor/github.com/blang/semver/sort.go, vendor/github.com/blang/semver/sql.go, vendor/modules.txt
fix: #92 
Current code calls `daemon.Client()` in many places and that method calls `start`. That's why I had to put cli version in a global variable.
=> use compatible (semver) daemon image

cmd/srcd/cmd/components.go, cmd/srcd/cmd/drivers.go, cmd/srcd/cmd/parse.go, cmd/srcd/cmd/sql.go
=> add help and validation for positional arguments

cmd/srcd/cmd/components.go, components/components.go, docs/commands.md
=> show only known images in components list

components/components.go
=> use bblfsh-drivers image

README.md
A drive-by improvement of Docker installation instructions in READEM:
- fix md formating in a list
- add macOS instructions
=> Doc: small reamde MD improvements

cmd/srcd-server/engine/web.go, components/components.go
it was failing because of the port only 😅
=> update bblfsh-web to 0.8.1

docker/docker.go
=> Fix version listing for images with more than one tag

cmd/srcd/cmd/parse.go, cmd/srcd/cmd/sql.go
=> Fix err message typos

README.md
It may be useful to point to the docs from GitHub `README.md`.
(if you'd move the link to any other part, suggestions are welcomed :wink: )
=> Add a link to the GitBook

docs/architecture.md
=> Using relative link to image

Makefile, README.md
=> Skips windows release

cmd/srcd/cmd/sql.go
=> Ensures the connection is ready before permitting to run sql queries

README.md
=> Add note about MacOS file sharing for the working directory

cmd/srcd/cmd/init.go
=> Fixes help message for init cmd

docker/docker.go
=> Increase the timeout for removing containers to 5 minutes

components/components.go
=> Update gitbase to v0.19.0-rc1

docs/commands.md
The command is implemented, but the docs were outdated.
=> Add docs for srcd components install

components/components.go
=> Update bblfsh to v2.11.8

README.md
=> Updates README.md to warn user about the workdir to use in Windows

components/components.go
Fix #282. Sadly it does not solve #281, see https://github.com/src-d/gitbase-web/issues/357
=> Update gitbase to gitbase-v0.19.0-rc2

cmd/srcd/cmd/init.go, cmd/srcd/daemon/daemon.go
=> Centralizes workdir transformation for Windows support

README.md
=> Improves documentation about Windows support

components/components.go
Fix #281 with the fix from https://github.com/src-d/gitbase-web/pull/358.
=> Update gitbase-web to v0.6.2

.travis.yml, cmd/srcd-server/Dockerfile
=> Update to go 1.12

cmd/srcd/cmd/version_test.go, cmd/test-utils/common.go
Part of #232.
Adds tests for `srcd version`.
=> Add integration tests for version cmd

cmd/srcd/cmd/web.go
Fix: #284 
Output:
```
$ srcd web sql
INFO[0003] this is taking a while, it might take a few more minutes while we install all the required images
INFO[0019] waiting for gitbase to be ready, done
INFO[0022] this is taking a while, if this is the first time you launch this web client, it might take a few more minutes while we install all the required images
Go to http://localhost:8080 for the gitbase web client. Press Ctrl-C to stop it.
```
It repeats "this is taking a while" if there are no images. Do you think is it a big problem?
I don't see how to avoid it without rewriting a lot.
=> make web sql wait for gitbase to be ready

cmd/srcd/cmd/parse.go
=> Shows supported languages when an unknown one is requested

cmd/srcd/cmd/init_test.go
Part of #232.
Adds tests for `srcd init`, adding tests that check that we are restarting gitbase when `init` is called with a different workdir, or the same workdir.
=> Add init integration tests for workdir changes

cmd/srcd/cmd/sql_test.go, cmd/test-utils/common.go, vendor/modules.txt
Part of #232.
Adds tests for `srcd sql`.
=> Add integration tests for sql cmd

cmd/srcd/config/config.go, cmd/srcd/daemon/daemon.go
=> Better config err msg

cmd/srcd/daemon/daemon.go
Closes #271.
This was tested with [this file](https://github.com/aws/aws-sdk-php/blob/master/src/data/ec2/2016-11-15/docs-2.json.php).
=> Increases the max size for received messages by deamon client

cmd/srcd/cmd/parse.go
=> Fixes log messages for long wait using parse command

cmd/srcd/cmd/web_test.go
Part of #232.
Tests for `web sql`, `web parse`.
=> Add integration tests for web cmd

cmd/srcd/cmd/web.go
I tested with changes from #354 and on master by re-running job multiple times.
Every time the tests passed correctly. So most probably it does fix the tests.
=> fix flaky web test

Makefile
=> Modifies makefile in order to handle integration testing for OSX

README.md
Latest release URL was not leading to latest release, but for all release page.
=> Update latest releases URL

cmd/srcd/cmd/stop_test.go, cmd/test-utils/common.go
Part of #232.
Tests for `srcd stop`
=> Add integration tests for stop cmd

cmd/srcd/cmd/sql_test.go
Fix: #333
To test locally for now it's necessary to do `rm -rf ~/.srcd/gitbase/`. It will be magically fixed when #355 lands in master.
=> add test for different work dirs with indexes

cmd/srcd/cmd/prune.go, cmd/srcd/daemon/daemon.go
fix: #352 
there is no test for it because prune tests pr isn't merged to the master yet
=> prune: remove gitbase indexes

cmd/srcd-server/engine/components.go, cmd/srcd-server/engine/engine.go, cmd/srcd-server/main.go, cmd/srcd/daemon/daemon.go
Fix: #349 
I didn't delete data directory yet. It's unused now. Do you want me to delete it in this pr or in a separate one? Or just keep it as it is right now in case we will need it later?
=> use docker volume for gitbase index

cmd/srcd-server/engine/sql.go
Closes #345, including the cherry picked commit from #346 and adding a comment to the value.
=> Set MaxAllowedPacket to 32M

CHANGELOG.md, api/config.go, cmd/srcd/cmd/web_test.go, cmd/srcd/config/config.go, cmd/srcd/daemon/daemon.go
=> Engine state

README.md, docs/architecture.md, docs/commands.md
=> Update docs according to current state of source{d} Engine

CHANGELOG.md, cmd/srcd/cmd/sql.go
=> fix input mode on windows in attach

cmd/srcd/cmd/web.go
=> Fixes channel buffer size for receiving signals

cmd/srcd/cmd/init.go, cmd/srcd/cmd/init_test.go, cmd/srcd/cmd/sql_test.go, cmd/srcd/cmd/web_test.go, run-integration-tests.bat
Fix: #348 
Please check commit messages for the explanation for each change.
=> Windows integration test

README.md
Improve & Fix README.md:
- Improve/fix markdown & HTML formatting & conformity to `markdownlint`
- Add sub-items to table of contents
- Improve readability of existing sections
- Add structure to sections for context/navigation
- Add extra content to many sections
Tried to keep commits rather atomic for ease of review.
=> Improve & Fix README.md

README.md
=> Adds link to init configuration from README.md

README.md
=> Makes more visible that Docker Toolbox is not supported

cmd/srcd/cmd/sql.go
most probably appeared due to incorrect merge
(before humanizef function was exiting)
Signed-off-by: Maxim Sukharev <max@smacker.ru>
=> fix unchecked errors in srcd sql

cmd/srcd-server/engine/components.go, docker/docker.go
=> Makes Gitbase workdir bind-mount read-only

CHANGELOG.md, components/components.go
=> Bumps bblfshd component version

cmdtests/prune_test.go, docker/docker.go
=> Adds checks when building Docker client

.travis.yml, cmdtests/gitbase_back_comp_test.go, cmdtests/sql_index_util.go, cmdtests/sql_test.go
I noticed that regression tests are broken. I've added a simple travis stage to at least check that these are buildable to avoid breaking them again in the future.
=> Fixes test regression

cmdtests/common.go, cmdtests/common_test.go
=> Fixes check in `StreamLinifier` for pending lines
